### PR TITLE
Fix clang-tidy 8 issues

### LINKED ISSUE #112: `make lint` fails with clang-tidy 8 (Ubuntu 19.04)
https://github.com/rootless-containers/slirp4netns/blob/v0.4.0-beta.1/main.c
```console
$ make lint
clang-tidy -warnings-as-errors='*' main.c slirp4netns.c api.c -- -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
2 warnings generated.
2 warnings generated.
2 warnings generated.
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:19: error: Potential memory leak [clang-analyzer-unix.Malloc,-warnings-as-errors]
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
                  ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:622:5: note: Calling 'parse_args'
    parse_args(argc, argv, &options);
    ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:12: note: Assuming the condition is true
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
           ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:5: note: Loop condition is true.  Entering loop body
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
    ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:397:9: note: Control jumps to 'case 97:'  at line 453
        switch (opt) {
        ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:454:35: note: Memory is allocated
            options->api_socket = strdup(optarg);
                                  ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:455:13: note:  Execution continues on line 395
            break;
            ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:12: note: Assuming the condition is true
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
           ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:5: note: Loop condition is true.  Entering loop body
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
    ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:397:9: note: Control jumps to 'case 97:'  at line 453
        switch (opt) {
        ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:455:13: note:  Execution continues on line 395
            break;
            ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:19: note: Potential memory leak
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
                  ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:446:17: error: Potential memory leak [clang-analyzer-unix.Malloc,-warnings-as-errors]
            if (access(options->userns_path, F_OK) == -1) {
                ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:622:5: note: Calling 'parse_args'
    parse_args(argc, argv, &options);
    ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:12: note: Assuming the condition is true
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
           ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:5: note: Loop condition is true.  Entering loop body
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
    ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:397:9: note: Control jumps to 'case -45:'  at line 444
        switch (opt) {
        ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:445:36: note: Memory is allocated
            options->userns_path = strdup(optarg);
                                   ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:446:17: note: Assuming the condition is false
            if (access(options->userns_path, F_OK) == -1) {
                ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:446:13: note: Taking false branch
            if (access(options->userns_path, F_OK) == -1) {
            ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:452:13: note:  Execution continues on line 395
            break;
            ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:12: note: Assuming the condition is true
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
           ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:395:5: note: Loop condition is true.  Entering loop body
    while ((opt = getopt_long(argc, argv, "ce:r:m:a:6hv", longopts, NULL)) !=
    ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:397:9: note: Control jumps to 'case -45:'  at line 444
        switch (opt) {
        ^
/home/suda/gopath/src/github.com/rootless-containers/slirp4netns/main.c:446:17: note: Potential memory leak
            if (access(options->userns_path, F_OK) == -1) {
                ^
2 warnings treated as errors
make: *** [Makefile:2133: lint] Error 2
```

```console
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 8.0.0

  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
clang-tidy seems to hate `strdup(optarg)` in the `while(getopt())` loop.

Fix #112

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
cc @gabibeyer @giuseppe

File: main.c [hunk 1]
```diff
@@ -460,45 +466,57 @@ static void parse_args(int argc, char *const argv[], struct options *options)
...
+            break;
         case 'v':
             version();
             exit(EXIT_SUCCESS);
+            break;
         default:
-            usage(argv[0]);
-            exit(EXIT_FAILURE);
+            goto error;
+            break;
```
Comment (giuseppe) [inline main.c]: the break here is not necessary.

What was wrong with the original code?  Does clang complain about it?

Comment (AkihiroSuda) [reply main.c]: the break is not necessary here but personally I prefer to have `break` everywhere.

The clang-tidy error is shown in #112 and fixed by moving `strdup(optarg)` out of the `while(getopt())` loop.
